language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script: 
  - phpunit

after_script:
  - php vendor/bin/coveralls -v
